spring:
  application:
    name: gymgenixs
  datasource:
    url: jdbc:h2:file:./gym
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format-sql: true
        ddl-auto: update
        show-sql: true

server:
  port: 8085

